---
title: "Mindard Redesign"
author: "Morgaine Westin"
date: "02/02/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(wesanderson)
library(ggimage)

troops <- as.data.frame(read.table("data/troops.txt", header=T))
cities <- as.data.frame(read.table("data/cities.txt", header=T))
temps <- as.data.frame(read.table("data/temps.txt", header=T))

scale <- function(x) {
  (x / 10000)
}
troops$survivors <- scale(troops$survivors)

troops$group <- as.factor(troops$group)
str(troops)


troops$long <- if

troops %>% filter(direction == 'A') %>%
ggplot() +
  geom_bar(mapping = aes(x = long, y = survivors, fill = group), stat = "identity") +
  coord_polar(start = 0) 


ggplot(troops) +
  geom_bar(mapping = aes(x = long, y = survivors, fill = direction), stat = "identity") +
  coord_polar(start = 0)
```

```{r, fig.height = 3}
ggplot(group1) +
  geom_bar(mapping = aes(x = lat, y = survivors, fill = direction), stat = "identity") +
  coord_polar(start = 0) 
```
```{r}

troops_sim <- read.csv("data/troops_sim_new.csv", header = T)
troops_sim$X <- as.integer(troops_sim$X)
str(troops_sim)

troops_sim2 <- troops_sim %>%
  bind_rows(troops_sim %>% filter(direction == 'R') %>%
              mutate(survivors = -survivors, direction = "-R")) 
```


```{r}
troops_sim2 %>% filter(direction == '-R' | direction == "A") %>%
  filter(group == 1) %>%
ggplot() +
  geom_bar(mapping = aes(x = X, y = survivors, fill = direction), stat = "identity", width) +
  scale_fill_manual(values = wes_palette("GrandBudapest2", 2), labels = c("Retreat", "Advance")) +
  guides(fill = guide_legend(reverse = TRUE)) 
  
```


```{r}
a <- troops_sim2 %>% filter(direction == "A") %>%
  filter(group == 1)
a$direction <- as.factor(a$direction)

b <- troops_sim2 %>%
  filter(group == 1 & direction == '-R')
```


```{r}
ggplot() +
  # advance
  geom_bar(data = a, mapping = aes(x = X, y = survivors), stat = "identity", fill = "#EFBC89")  +
  # retreat
  geom_bar(data = b, mapping = aes(x = X, y = survivors, fill = temperature), stat = "identity") + scale_fill_gradient(low = "#6398CD", high = "#EA9BB3") +
  theme_minimal() 
```

```{r}
ggplot() +
  # advance
  geom_bar(data = a, mapping = aes(x = X, y = survivors), stat = "identity", fill = "#EFBC89")  +
  # retreat
  geom_bar(data = b, mapping = aes(x = X, y = survivors, fill = temperature), stat = "identity") + scale_fill_gradient(low = "#6398CD", high = "#EA9BB3") +
  theme_minimal() 
```